name: advanced_video_player
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.advanced_video_player
        pluginClass: AdvancedVideoPlayerPlugin
      ios:
        pluginClass: AdvancedVideoPlayerPlugin
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

