name: advanced_video_player
description: "Un reproductor de video avanzado para Flutter con controles modernos, Picture-in-Picture, Google Cast, AirPlay y diseño personalizable."
version: 0.0.3
homepage: https://github.com/pablomelobt/advanced_video_player.git
repository: https://github.com/pablomelobt/advanced_video_player.git
issue_tracker: https://github.com/pablomelobt/advanced_video_player/issues
documentation: https://github.com/pablomelobt/advanced_video_player.git#readme

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.advanced_video_player
        pluginClass: AdvancedVideoPlayerPlugin
      ios:
        pluginClass: AdvancedVideoPlayerPlugin
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

